<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class  InsertDataIntoCitiesTable extends Migration
{
    public function up()
    {
        $cities = [
            'Aerschot (Aarschot)',
            'Alost (Aalst)',
            'Andenne',
            'Ans',
            'Antoing',
            'Anvers (Antwerpen)',
            'Arlon',
            'Ath',
            'Aubange',
            'Audembourg (Oudenburg)',
            'Audenarde (Oudenaarde)',
            'Bastogne',
            'Beaumont',
            'Beauraing',
            'Beringen',
            'Bilzen',
            'Binche',
            'Blankenberghe (Blankenberge)',
            'Bouillon',
            'Braine-le-Comte',
            'Brée (Bree)',
            'Bruges (Brugge)',
            'Bruxelles (Brussel)',
            'Charleroi',
            'Châtelet',
            'Chièvres',
            'Chimay',
            'Chiny',
            'Ciney',
            'Comines-Warneton',
            'Courtrai (Kortrijk)',
            'Couvin',
            'Damme',
            'Deinze',
            'Diest',
            'Dilsen-Stokkem',
            'Dinant',
            'Dixmude (Diksmuide)',
            'Durbuy',
            'Eeklo',
            'Enghien',
            'Eupen',
            'Fleurus',
            'Florenville',
            'Fontaine-l\'Évêque',
            'Fosses-la-Ville',
            'Furnes (Veurne)',
            'Gand (Gent)',
            'Geel',
            'Gembloux',
            'Genappe',
            'Genk',
            'Gistel',
            'Grammont (Geraardsbergen)',
            'Hal (Halle)',
            'Halen',
            'Hamont-Achel',
            'Hannut',
            'Harelbeke',
            'Hasselt',
            'Herck-la-Ville (Herk-de-Stad)',
            'Herentals',
            'Herstal',
            'Herve',
            'Hoogstraten',
            'Houffalize',
            'Huy',
            'Iseghem (Izegem)',
            'Jodoigne',
            'La Louvière',
            'La Roche-en-Ardenne',
            'Landen',
            'Le Rœulx',
            'Léau (Zoutleeuw)',
            'Lessines',
            'Leuze-en-Hainaut',
            'Liège',
            'Lierre (Lier)',
            'Limbourg',
            'Lo-Reninge',
            'Lokeren',
            'Lommel',
            'Looz (Borgloon)',
            'Louvain (Leuven)',
            'Maaseik',
            'Malines (Mechelen)',
            'Malmedy',
            'Marche-en-Famenne',
            'Menin (Menen)',
            'Messines (Mesen)',
            'Mons (Bergen)',
            'Montaigu-Zichem (Scherpenheuvel-Zichem)',
            'Mortsel',
            'Mouscron',
            'Namur',
            'Neufchâteau',
            'Nieuport (Nieuwpoort)',
            'Ninove',
            'Nivelles (Nijvel)',
            'Ostende (Oostende)',
            'Ottignies-Louvain-la-Neuve',
            'Peer',
            'Péruwelz',
            'Philippeville',
            'Poperinge',
            'Renaix (Ronse)',
            'Rochefort',
            'Roulers (Roeselare)',
            'Saint-Ghislain',
            'Saint-Hubert',
            'Saint-Nicolas (Sint-Niklaas)',
            'Saint-Trond (Sint-Truiden)',
            'Saint-Vith (Sankt Vith)',
            'Seraing',
            'Soignies',
            'Spa',
            'Stavelot',
            'Termonde (Dendermonde)',
            'Thourout (Torhout)',
            'Thuin',
            'Tielt',
            'Tirlemont (Tienen)',
            'Tongres (Tongeren)',
            'Tournai',
            'Tubize',
            'Turnhout',
            'Verviers',
            'Vilvorde (Vilvoorde)',
            'Virton',
            'Visé',
            'Walcourt',
            'Waregem',
            'Waremme',
            'Wavre',
            'Wervicq (Wervik)',
            'Ypres (Ieper)',
            'Zottegem',
        ];

        foreach ($cities as $city) {
            DB::table('cities')->insert([
                'name' => $city,
            ]);
        }
    }

    public function down()
    {
        // Pour supprimer les données insérées, vous pouvez exécuter la requête inverse
        DB::table('cities')->truncate();
    }
}